---
- name: "Configure certificates"
  block:
    - name: "Ensure cacerts directory is present"
      file:
        path: "{{ openldap_client_conf_path }}/{{ openldap_client_cacerts_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Ensure certs directory is present"
      file:
        path: "{{ openldap_client_conf_path }}/{{ openldap_client_certs_directory }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Install CA Cert if defined"
      copy:
        content: "{{ openldap_client_ca_cert_content }}"
        dest: "{{ openldap_client_ca_cert }}"
      when: openldap_client_ca_cert is defined

  when: openldap_client_manage_certs | bool

- name: "Manage ldap.conf configuration"
  template:
    src: "{{ openldap_client_conf_template }}"
    dest: "{{ openldap_client_conf_path }}/{{ openldap_client_conf_filename }}"
    owner: root
    group: root
    mode: 0644
  when: openldap_client_manage_config | bool
